application: cs-174
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /images
  static_dir: images

- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: .*
  script: main.app
